# Internal routes
_ezpublishLocation:
    path: /content/location/{locationId}/{viewType}/{layout}
    defaults:
        _controller: ezpublish.controller.content.view:viewLocation
        viewType: full
        layout: true

_ezpublishUserHash:
    pattern: /_ez_user
    requirements:
        method: AUTHENTICATE
